### ISSUE TITLE
hw01 ready for grading

### ISSUE THREAD

**Issue by juansbr7** [juansbr7/STAT545-hw01-Bonilla-Juan#1]
@vincenzocoia @gvdr @ksedivyhaley @joeybernhardt @mynamedaike @pgonzaleze @derekcho

**Comment by margotgunning** [comment]
Hey Juan ( @juansbr7 )

I think you did a great job, and gave a good first submission!

Your README file demonstrated a good use of the different fonts (bold, italics), headers, and listing ability.  It was awesome how you provided links to your other files in your repo; it made them very easy to access.  Your GitHub experience paragraph gave a very thorough overview of your progress, and it was nice how you attached the cheat sheet.  A suggestion I have is to maybe direct people to sections that you found helpful because there is quite a bit on that sheet.   I think its great you edited both on GitHub and locally, and had no/few issues with merge conflitcs etc to get used to it.

Your more info Readme was informative, and I learned a lot more about you from your website.  I hope you're liking your program so far!  I also have some experience with R and Python; I do like Python a bit better (its more intuitive to me), but R is also very easy to use, and has quite a few resources.

Overall, good job, and good luck with the next assignment,

Cheers,

Margot
.

**Comment by mlawre01** [comment]
Hi Juan,

Thanks for sharing your repo with me. 

README

- very informative readme file, the links were helpful for navigating your repo (in the future I will be putting links in mine!) 
- the extra .rmd file was a nice touch, I have also lived in Ontario and Alberta
- good use of different headers/fonts etc. throughout your documents 
- overall, nice job

Hope you enjoy the rest of the course. 

Cheers,

Mackenzie

**Comment by mlawre01** [comment]
Hi Juan,

Thanks for sharing your repo with me. 

README

- very informative readme file, the links were helpful for navigating your repo (in the future I will be putting links in mine!) 
- the extra .rmd file was a nice touch, I have also lived in Ontario and Alberta
- good use of different syntax throughout your documents 
- overall, nice job 

Hope you enjoy the rest of the course. 

Cheers,

Mackenzie

**Comment by derekcho** [comment]
Hi @juansbr7! Here are some comments about your hw01:

Your README file is great and includes all of the necessary elements. It looks neat and includes many different Markdown syntaxes. You should probably include the stuff you put in juanhw1.Rmd in your README file as well for this assignment since they fit well as an introduction for yourself. 

I did not find the gapminder exploration in your repo.

Note: your mark (check minus, check, check plus) will be distributed later.
