### ISSUE TITLE
HW3 ready for grading

### ISSUE THREAD

**Issue by juansbr7** [juansbr7/STAT545-hw01-Bonilla-Juan#3]

**Comment by yidie** [comment]
Hi Juan, here are some comments:

- Get the maximum and minimum of GDP per capita for all continents.
Good job creating the table and graph. It would be better if you could label the graph properly by adding a title. You also made observations about Asia's gdp, which is good to see.

- Compute a trimmed/weighted mean of life expectancy for different years.
Good job calculating both trimmed and weighted mean of lifeExp. For the companion graph, plotting those means might be better instead of the boxplot since we want to know something about the means.

- How is life expectancy changing over time on different continents?
Good job interpreting the relationship between gdpPercap and lifeExp. Nice ggplot which uses color to differentiate continent and size of the points to represent the magnitude of gdpPercap. Good visualization.

- Report the absolute and/or relative abundance of countries with low life expectancy over time by continent.
Good job using `ifelse` function to classify high/low lifeExp! It would be better if you can illustrate what you are trying to show by the ggplot or make some observations on the plot.

- Interesting observation about the lifeExp in Rwanda. For the 10 countries with the lowest lifeExp growth, I am a bit confused with what the table shows. I saw that in your code, you took the difference of lifeExp with respect to the stating lifeExp and then arrange that difference to find the lowest ten. The problem is that these lowest would come from different years and you have same countries appearing in the table several times. I get your idea, but you might want to fix other variables while comparing the differences, like what you did for "the three countries with lowest lifeExp" which makes more sense since you fix the variable year to be 2007. But you really put good efforts!

- The very last plot is beautifully made, although I am not sure why you add the regression line to it.

- Overall, you did a very good job finishing at least three tasks as well as doing some extra! Your md is organized clearly which makes it easy to see which task you are doing and what the code is doing. There are a lot of efforts and good attempt in terms of exploring the dataset. Detailed reflections as well.

Thanks,
Yidie

**Comment by derekcho** [comment]
Hi @juansbr7! Here are some comments about your hw03

-	Your repo could use a little more organization, please put things into folders (one folder per assignment is recommended). Later you will have more than one or two files per assignment and each should have its own README
-	You can get rid of warning messages in your markdown file by loading libraries with this command instead suppressStartupMessages(library(tidyverse)). The messages are fine in R, but make your markdown report look messy.
-	You should add section headers to make it clearer when you are beginning a new task. Also, it makes your report look more organized!
-	Nice job getting tables formatted with knitr!!
-	Good coding style, easy to read and efficient!
-	Most plots are generally visually appealing and self contained
-	For your high/low life expectancy plot, I would suggest that you transpose the axes (switch X and Y axes), it is pretty hard to tell what is going on in those plots. In addition, you could also rotate the X axis labels since they are tough to read
-	For your last plot, the patterns don’t really look linear, so I don’t think that it makes sense to fit a linear curve to the data. I would suggest that you just use the default of a smoothing spline in this case for each group rather than combined [eg. geom_smooth(aes(color = country),method=”loess”)]
-	Nice work overall!

Note: your mark (check minus, check, check plus) will be distributed later.

**Comment by shadowforti** [comment]
Hello Juan 

You have done a great job in creating the table using knitr. You have present the data set result with various style of plots which I found to be interesting. You also have explained your steps well and it is easy to follow. I could see that you are well capable using the dplyr to manipulate the data and ggplot for plotting. You have also included the reflection.  (I need to refresh the stat knowledge too). However, in my opinion, I think it would be better if you could creat a folder for each homework and have a header for each task. 

Overall, the work is great and I really like your plots. I have learnt different ways to present the data.
