### ISSUE TITLE
homework 5 ready

### ISSUE THREAD

**Issue by juansbr7** [juansbr7/STAT545-hw01-Bonilla-Juan#5]

**Comment by arsbar24** [comment]
Hi Juan,

I enjoyed reading your assignment. Your enthusiasm for your work is palpable, and makes your work a treat to read.

I like how you walked me through your process and showed me how you checked your progress in the Oceania section. It made your work easy to follow and learn from. You can make this even easier by using these descriptions to break up your code chunks—e.g. cycle through description, code, output, description, code, etc.—this makes it easier to parse each code chunk as there's a lot less for the reader to keep track of at a time.

Your graphs demonstrate an impressive level of proficiency with a variety of plot functions and are very aesthetically pleasing; however there are a couple stylistic tweaks I would recommend depending on what characteristic of the data you’re trying to draw attention to (I understand it may not have been your priority for the assignment, but it could be something to focus on since I see little other room for improvement).

For example, I think it’s a bit misleading to have the life expectancy chart place the x-axis at y=20 years (from a quick glance it looks like there’s an African country with a life expectancy of 10 years at one point), and a log x axis might make it easier to perceive growth in your population chart beyond the first 6 countries. 

The weird foods section was nice and fun, but I found the last graph a little confusing—I don’t think bar charts are the best way to show categorical variables. For a while I thought you ordered the factors by your subjective ‘weirded-outness’ by the different foods and was surprised someone would find fertilized egg less weird than guinea pig or frog legs.

All in all, an excellent assignment. I’d rate it a high check-plus.

Alistair

**Comment by Alexander-Morin** [comment]
Juan's repo is clearly organized, with links to the relevant assignments. 

As a suggestion, you can directly add message = False and warning = False to the start of your R code snippet to hide library message
\```{r, message = False...

Oceania is dropped, and the process of needing to use droplevels is clearly explained.
An ordered plot is also shown to demonstrate its increased ease of reading.

Suggestion: some of your R calls (particularly ggplot calls) are rather long on one line, and require horizontal scrolling to read the full line. In settings you can set a margin that defaults to '80' - if you keep everything in this margin (splitting arguments to new lines where required), it helps keep your code consistent and easier to read.

Saving plots are demonstrated.

The dollar overlay on the plots is a nice addition. It wasn't immediately clear that the +/- were reflect differences in min/max gdp _across years._

Multiple attributes are applied to a graph to demonstrate ways of visualizing information.

The life expectancy plot with bounds, mean/median and facetting was really well done. 

Overall good and fun work!

**Comment by derekcho** [comment]
Hi @juansbr7! Here are some comments about your hw05:
-	Good work on the first task, you demonstrated the use of droplevels() correctly and the task was well done. A minor suggestion: I would use the function levels() to show that Oceania was dropped rather than str() since it highlights the point better. Good job though!
-	Excellent side by side graphic showing the difference between ordered and unordered levels. Another minor point: I cannot see any use of arrange() in this part though.
-	File I/O and saving figures to a file was done correctly
-	When you are reading using readRDS (or any other long chunk of code), try to split it up into several lines to improve readability even though your code is correct
-	Although it was a cool idea, it isn’t really clear what the height of the bars in the bar plot correspond to (the one with the weird food). However, the rest of your graphs were well done and very appealing!
-	Your repo looks much more organized now!
-	Nice work overall! Great work in STAT 545A!

Note: your mark (check minus, check, check plus) will be distributed later.
